# local開発用
version: "3.7"
services:
  db:
    image: postgres:13-alpine
    container_name: "ibis-dev"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "15432:5432"
volumes:
  database:
    driver: local
